name: Bug report
description: Report a bug or unexpected behavior
labels: [fix]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Please describe the bug clearly and provide steps to reproduce it if possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: e.g. Timer doesn't reset properly after reaching delay
    validations:
      required: true

  - type: checkboxes
    id: todo
    attributes:
      label: Todo
      options:
        - label: Reproduce the bug
        - label: Fix the issue
        - label: Add test case
        - label: Update related code

  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: Additional notes, error messages, or screenshots
      placeholder: Logs, screenshots, or other useful info
